---
- name: Install the required packages
  hosts: all
  sudo: True
  roles:
    - role: ANXS.nodejs
    - role: rvm_io.rvm1-ruby
  vars:
    nodejs_version: '0.12.7'
    nodejs_install_method: 'binary'
    rvm1_rubies:
      - 'ruby-2.1.5'
      - 'ruby-2.2.2'
    rvm1_install_flags: '--user-install'
    rvm1_install_path: '/home/vagrant/.rvm'
    rvm1_user: 'vagrant'
    dotfiles:
      - arangosh.rc
      - bundle
      - config
      - csirc
      - gemrc
      - gitconfig
      - irbrc
      - tmux.conf
      - tmuxinator
      - vimrc
      - zsh
      - zshrc
    apt_packages:
      - chicken-bin
      - clisp
      - cloc
      - elixir
      - emacs
      - git
      - git-svn
      - golang
      - graphviz
      - haskell-platform
      - htop
      - imagemagick
      - ispell
      - jq
      - libcurl3
      - libcurl3-gnutls
      - libcurl4-openssl-dev
      - libpq-dev
      - libxml2
      - maven
      - openjdk-8-jdk
      - optipng
      - postgresql
      - redis-server
      - silversearcher-ag
      - subversion
      - swi-prolog
      - tig
      - tmux
      - tree
      - wget
      - zsh
    vim_packages:
      vim-pathogen: tpope/vim-pathogen
      vim-colors-solarized: altercation/vim-colors-solarized
      vim-polyglot: sheerun/vim-polyglot
      vim-fugitive: tpope/vim-fugitive
      vim-commentary: tpope/vim-commentary
      vim-dispatch: tpope/vim-dispatch
      vim-surround: tpope/vim-surround
      vim-repeat: tpope/vim-repeat
      vim-emoji: junegunn/vim-emoji
      vim-textobj-user: kana/vim-textobj-user
      vim-textobj-rubyblock: nelstrom/vim-textobj-rubyblock
      rainbow: luochen1990/rainbow
      paredit.vim: vim-scripts/paredit.vim
      syntastic: scrooloose/syntastic
      ctrlp.vim: kien/ctrlp.vim
      vim-rspec: thoughtbot/vim-rspec
      vim-proto: garyharan/vim-proto
    npm_packages:
      - npm
      - jslint
      - jshint
      - jscs
    marks:
      c: /home/vagrant/Code
  tasks:
    - name: Add Erlang Solutions key
      apt_key: url='http://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc'
    - name: Add Erlang Solutions APT Repository
      apt_repository: repo='deb http://packages.erlang-solutions.com/ubuntu vivid contrib' state=present
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe
    - name: Install missing packages
      apt: name={{ item }}
      with_items: apt_packages
    - name: Link Dotfiles
      file: path=/home/vagrant/.{{ item }} state=link src=/home/vagrant/Code/dotfiles/tilde/{{ item }}
      with_items: dotfiles
    - name: Install or update Vim plugins
      git: repo=https://github.com/{{ item.value }} dest=/home/vagrant/.vim/bundle/{{ item.key }}
      with_dict: vim_packages
    - name: Set default shell for Vagrant user
      user: name=vagrant shell=/bin/zsh
    - name: Install global NPM packages
      npm: name={{ item }} global=yes state=latest
      with_items: npm_packages
    - name: Create the marks directory
      file: path=/home/vagrant/.marks state=directory
    - name: Configure the marks
      file: path=/home/vagrant/.marks/{{ item.key }} state=link src={{ item.value }}
      with_dict: marks
