---
- name: Install the required packages
  hosts: all
  vars:
    full_name: "Lucas Dohmen"
    email: "lucas@dohmen.io"
    url: "https://lucas.dohmen.io"

    nodejs_version: 10.x
    ruby_version: 2.5

    apt_keys:
      68576280: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
      0EBFCD88: 'https://download.docker.com/linux/ubuntu/gpg'
    apt_repositories:
      - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} bionic main'
      # TODO: Replace with bionic when it is available
      - 'deb https://download.docker.com/linux/ubuntu artful stable'
      - 'ppa:brightbox/ruby-ng'
    apt_packages:
      - asciinema
      - build-essential
      - curl
      - docker-ce
      - gnupg2
      - gnupg-agent
      - jq
      - nodejs
      - openjdk-11-jdk-headless
      - python3-pip 
      - ragel
      - ruby{{ ruby_version }}
      - ruby{{ ruby_version }}-dev
      - silversearcher-ag
      - tig
      - tree
      - zsh
    vim_packages:
      editorconfig-vim: editorconfig/editorconfig-vim
      neomake: benekastah/neomake
      vim-colors-solarized: altercation/vim-colors-solarized
      vim-commentary: tpope/vim-commentary
      vim-polyglot: sheerun/vim-polyglot
      vim-surround: tpope/vim-surround
      vim-racer: racer-rust/vim-racer
      vim-repeat: tpope/vim-repeat
    npm_packages:
      - alex
      - heroku-cli
    ruby_gems:
      - awesome_print
      - bundler
      - electric_monk
      - manpages
      - mdless
      - pry
      - rubocop
    pip_packages:
      - awscli
      - docker-compose
      - youtube-dl
    marks:
      c: /home/vagrant/Code
      d: /vagrant
    spell_files:
      - en.utf-8.spl
      - en.utf-8.sug
      - de.utf-8.spl
      - de.utf-8.sug

  tasks:
    - name: Find all Dotfiles
      shell: ls -1 /vagrant/tilde
      register: dotfiles
    - name: Link Dotfiles
      file:
        path: /home/vagrant/.{{ item }}
        src: /vagrant/tilde/{{ item }}
        owner: vagrant
        group: vagrant
        state: link
      with_items: "{{ dotfiles.stdout_lines }}"

    - name: Fix up SSH for proper Socket Forwarding
      lineinfile:
        path: /etc/ssh/sshd_config
        line: 'StreamLocalBindUnlink yes'
      become: true

    - name: Create ~/.gnupg
      file: path=/home/vagrant/.gnupg state=directory mode=0700
    - name: Link gnupg files
      file:
        path: /home/vagrant/.gnupg/{{ item }}
        src: /vagrant/gnupg/{{ item }}
        owner: vagrant
        mode: 0600
        group: vagrant
        state: link
      with_items:
        - gpg.conf
        - pubring.gpg
        - trustdb.gpg

    - name: Add APT Keys
      apt_key: url="{{ item.value }}" id="{{ item.key }}"
      with_dict: "{{ apt_keys }}"
      become: true
    - name: Add APT Repositories
      apt_repository: repo="{{ item }}" state=present
      with_items: "{{ apt_repositories }}"
      become: true
    - name: Install aptitude
      apt: name=aptitude
      become: true
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe cache_valid_time=86400
      become: true
    - name: Install missing packages
      apt: name={{ item }}
      with_items: "{{ apt_packages }}"
      become: true

    - name: Set defaults for Vagrant user
      user:
        name: vagrant
        shell: /bin/zsh
        groups: docker
        append: yes
      become: true

    - name: Install ZSH Syntax Highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting
        dest: /home/vagrant/.zsh/plugins/zsh-syntax-highlighting

    - name: Set the timezone
      copy:
        dest: /etc/timezone
        content: "Europe/Berlin"
      become: true

    - name: Create the Code directory
      file: path=/home/vagrant/Code state=directory
    - name: Create the marks directory
      file: path=/home/vagrant/.marks state=directory
    - name: Configure the marks
      file: path=/home/vagrant/.marks/{{ item.key }} state=link src={{ item.value }} force=yes
      with_dict: "{{ marks }}"

    - name: Install default Ruby gems
      gem: name={{ item }}
      with_items: "{{ ruby_gems }}"

    - name: NPM Config
      file:
        path: /home/vagrant/.npmrc
        state: touch
    - name: Set NPM author name
      lineinfile:
        path: /home/vagrant/.npmrc
        regexp: '^init-author-name'
        line: 'init-author-name={{ full_name }}'
    - name: Set NPM author email
      lineinfile:
        path: /home/vagrant/.npmrc
        regexp: '^init-author-email'
        line: 'init-author-email={{ email }}'
    - name: Set NPM author url
      lineinfile:
        path: /home/vagrant/.npmrc
        regexp: '^init-author-url'
        line: 'init-author-url={{ url }}'
    - name: Set NPM prefix
      lineinfile:
        path: /home/vagrant/.npmrc
        regexp: '^prefix'
        line: 'prefix=/home/vagrant/.npm'

    - name: Install default NPM packages
      npm: name={{ item }} global=yes
      with_items: "{{ npm_packages }}"

    - name: Install or update vim plugins
      git: repo=https://github.com/{{ item.value }} dest=/home/vagrant/.vim/pack/bundle/start/{{ item.key }}
      with_dict: "{{ vim_packages }}"
    - name: Create spell directory
      file: path=/home/vagrant/.vim/spell state=directory
    - name: Install spell files for vim
      get_url: url=http://ftp.vim.org/pub/vim/runtime/spell/{{ item }} dest=/home/vagrant/.vim/spell/{{ item }}
      with_items: "{{ spell_files }}"

    - name: Install pips
      pip:
        name: "{{ item }}"
        state: present
        executable: pip3
      with_items: "{{ pip_packages }}"
      become: true

    - name: Install leiningen
      get_url:
        url: https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        dest: /usr/local/bin/lein
        mode: +x
      become: true

    - name: Download fzf
      git: repo=https://github.com/junegunn/fzf.git dest=/home/vagrant/.fzf
    # TODO: Only do this if fzf was updated
    - name: Install fzf
      command: '/home/vagrant/.fzf/install --key-bindings --completion --no-update-rc --no-bash'
